const MAX_COMMUNITY_NAME = 20

const ROOT_SUBMIT_ROUTE = 'submit'
const USER_SUBMIT_ROUTE = 'user-name-submit'
const COMMUNITY_SUBMIT_ROUTE = 'r-name-submit'

export {
  MAX_COMMUNITY_NAME,
  ROOT_SUBMIT_ROUTE,
  USER_SUBMIT_ROUTE,
  COMMUNITY_SUBMIT_ROUTE,
}